[2025-08-15T18:54:06.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T18:54:06.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.extract_transform scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T18:54:06.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_daily_7am.extract_transform scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T18:54:06.672+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-15T18:54:06.690+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_transform> on 2025-08-14 00:00:00+00:00
[2025-08-15T18:54:06.700+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_daily_7am', 'extract_transform', 'scheduled__2025-08-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_mysql_dag.py', '--cfg-path', '/tmp/tmppm87x6pe']
[2025-08-15T18:54:06.703+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_transform
[2025-08-15T18:54:06.703+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=427) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-15T18:54:06.704+0000] {standard_task_runner.py:63} INFO - Started process 429 to run task
[2025-08-15T18:54:06.794+0000] {task_command.py:426} INFO - Running <TaskInstance: excel_to_mysql_daily_7am.extract_transform scheduled__2025-08-14T00:00:00+00:00 [running]> on host 4973bafe0a32
[2025-08-15T18:54:07.112+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_daily_7am' AIRFLOW_CTX_TASK_ID='extract_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-14T00:00:00+00:00'
[2025-08-15T18:54:07.112+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T18:54:07.129+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T18:54:07.130+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/excel_to_mysql_dag.py", line 46, in extract_transform
    xls = pd.read_excel(EXCEL_PATH, sheet_name=None, dtype=str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-08-15T18:54:07.153+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=excel_to_mysql_daily_7am, task_id=extract_transform, run_id=scheduled__2025-08-14T00:00:00+00:00, execution_date=20250814T000000, start_date=20250815T185406, end_date=20250815T185407
[2025-08-15T18:54:07.183+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_transform (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 429)
[2025-08-15T18:54:07.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-15T18:54:07.240+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T18:54:07.246+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
